on:
  push:
    tags: ["v*"]
    branches: ["**"]
  pull_request:

name: Build and deploy
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build & test
        run: yarn ci

      - name: Run Integration tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: yarn test:it

  deploy:
    if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v'))
    needs: build
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Install vsce and deps
        run: |
          yarn global add vsce
          yarn install
      - name: Publish
        run: |
          echo $RELEASE_VERSION
          vsce publish -p $VSCODE_TOKEN --no-git-tag-version ${RELEASE_VERSION:1}
        env:
          VSCODE_TOKEN: ${{ secrets.VSCODE_TOKEN }}
